program: train.py
method: bayes
metric:
  name: val.overall_f1
  goal: maximize
parameters:
  learning_rate:
    min: 0.00001
    max: 0.0001
    distribution: log_uniform
  batch_size:
    values: [8, 16, 32]
  dropout:
    min: 0.1
    max: 0.3
    distribution: uniform
  num_layers:
    values: [2, 3, 4]
  hidden_size:
    values: [768, 1024, 1536]
  aspect_loss_weight:
    min: 0.5
    max: 1.5
    distribution: uniform
  opinion_loss_weight:
    min: 0.5
    max: 1.5
    distribution: uniform
  sentiment_loss_weight:
    min: 0.5
    max: 1.5
    distribution: uniform